name: build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build platform"
        required: true
        default: "linux"

env:
  GO_VERSION: "1.24"
  FLUTTER_VERSION: "3.24.5"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: master
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev libayatana-appindicator3-1 libayatana-appindicator3-dev rpm

      - name: Build RPM Only
        env:
          VERSION: "1.8.2" 
        run: |
          go build -tags nosqlite -ldflags="-w -s -X github.com/GopeedLab/gopeed/pkg/base.Version=$VERSION" -buildmode=c-shared -o ui/flutter/linux/bundle/lib/libgopeed.so github.com/GopeedLab/gopeed/bind/desktop
          go build -ldflags="-w -s" -o ui/flutter/assets/exec/host github.com/GopeedLab/gopeed/cmd/host
          go build -ldflags="-w -s" -o ui/flutter/assets/exec/updater github.com/GopeedLab/gopeed/cmd/updater

          cd ui/flutter

          mkdir -p linux/packaging/rpm
          
          RPM_ARCH="x86_64"
          if [[ "$(uname -m)" == "aarch64" ]]; then
            RPM_ARCH="aarch64"
          fi
          
          cat << EOF > linux/packaging/rpm/make_config.yaml
          display_name: Gopeed
          summary: A modern download manager
          group: Applications/Internet
          license: GPL-3.0
          packager: GopeedLab
          url: https://gopeed.com
          icon: assets/icon/icon.svg
          build_arch: $RPM_ARCH
          EOF

          cat << EOF > distribute_options.yaml
          output: dist/
          releases:
            - name: linux
              jobs:
                - name: rpm
                  package:
                    platform: linux
                    target: rpm
                    build_args:
                      dart-define:
                        UPDATE_CHANNEL: linuxRpm
          EOF

          dart pub global activate -sgit https://github.com/GopeedLab/flutter_distributor.git --git-path packages/flutter_distributor
          flutter_distributor release --name linux
          cd dist/*

          ARCH="amd64"
          if [[ "${{ matrix.os }}" == *-arm ]]; then
            ARCH="arm64"
          fi

          if ls gopeed-*-linux.rpm 1> /dev/null 2>&1; then
            mv gopeed-*-linux.rpm Gopeed-v${VERSION}-linux-${ARCH}.rpm
          else
            echo "Error: RPM file not found!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gopeed-rpm-${{ matrix.os }}
          path: ui/flutter/dist/*/*.rpm
